Fix missing-prototypes
parole-powermanager.c:104:1: error: no previous prototype for 'parole_power_manager_dbus_init' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>