build: Explicitly depend on gstreamer-tag
Fixes the following on NixOS:

mpris2-provider.c:29:10: fatal error: gst/tag/tag.h: No such file or directory
   29 | #include <gst/tag/tag.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

Both gstreamer-base-1.0.pc and gstreamer-tag-1.0.pc has `Cflags: -I${includedir}/gstreamer-1.0`,
but they are provided by two different packages in NixOS (gstreamer, gst-plugins-base),
and have different `includedir`.