Fix missing-prototypes
parole-powermanager.c:104:1: error: no previous prototype for 'parole_power_manager_dbus_init' [-Werror=missing-prototypes]
parole-player.c:538:10: error: no previous prototype for 'parole_player_get_playlist_visible' [-Werror=missing-prototypes]
parole-player.c:542:10: error: no previous prototype for 'parole_player_get_volume_visible' [-Werror=missing-prototypes]
parole-medialist.c:1933:7: error: no previous prototype for 'parole_media_list_store_get_uint' [-Werror=missing-prototypes]
parole-medialist.c:1989:8: error: no previous prototype for 'parole_media_list_store_get_str' [-Werror=missing-prototypes]
parole-medialist.c:2025:7: error: no previous prototype for 'parole_media_list_get_row_entry_order' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>